apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: my-trusted-quarkus-app 
  janus-idp.io/tekton: my-trusted-quarkus-app
  backstage.io/kubernetes-id: my-trusted-quarkus-app
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: my-trusted-quarkus-app
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  