apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: my-trusted-quarkus-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-trusted-quarkus-app 
  name: my-trusted-quarkus-app
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: my-trusted-quarkus-app
    weight: 100 
