apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: my-trusted-quarkus-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-trusted-quarkus-app 
  name: my-trusted-quarkus-app
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: my-trusted-quarkus-app 
